lawyered/urls.py
from django.conf.urls import url
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, UserRegistrationForm
from django.contrib.auth.decorators import login_required

from django.contrib.auth.views import logout
from . import views
app_name = 'lawyered'
urlpatterns = [
    url(r'^$', views.index, name='index'),
#    url(r'^login/$', views.login, {'template_name' : 'login.html'}),
    url(r'^login/$', views.login, name='login'),
    url(r'^login/$',login, name = 'login'),
	url(r'^logout/$',logout, {'next_page': '/lawyered'}, name='logout'),
	url(r'^register/$', views.register, name='register'),
    url(r'^dashboard/$',views.dashboard,name='dashboard'),
	url(r'^search/$', views.person_list, name='search'), 
	url(r'^divorce/$', views.divorce, name='divorce'),
	

]
#url(r'^$', views.dashboard, name='dashboard'),url(r'^logout-then-login/$','django.contrib.auth.views.logout_then_login',name='logout_then_login'),url(r'^login/$', views.user_login,name='login'),

project1/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # Examples:
    # url(r'^$', 'project1.views.home', name='home'),
    url(r'^lawyered/', include('lawyered.urls')),
#    url(r'^ath/', include('laath.urls')),
	url(r'^login/$', views.login, {'template_name' : 'login.html'}),
    url(r'^admin/', include(admin.site.urls)),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

lawyered/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class person(models.Model):
	name = models.CharField(max_length=250)
	area = models.CharField(max_length=250)
	specialization = models.CharField(max_length=250)
	details = models.TextField()
	image = models.ImageField(upload_to='lawyered/media/',blank=True)
def __str__(self):
	return self.title	
	
# Create your models here.

lawyered/forms.py
from django import forms
from django.contrib.auth.models import User
import datetime
from datetime import timedelta, datetime
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
        
    def clean_password2(self):
        password1 = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password2')
        if password1 and password1 != password_confirm:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

class SearchForm(forms.Form):
    query = forms.CharField()

ASSETS = (
    ('residential_property', 'Residential Property'),
    ('investment_property', 'Investmant Property'),
    ('investment_account', ' Investment Account(s) (stocks, bonds, mutual funds, etc.) '),
    ('bank_account','Bank Account(s)'),
    ('pension', 'pension, or other retirement plan'),
    ('business','Business interest(s)'),
    ('personal_property','Personal property (jewelry, cars, furniture, appliances, etc.) '),
    ('others','Others'),
    
)

TESTS = ( 
    ('Breathalyzer','breathalyzer'),
    ('Balance and coordination tests','balance and coordination tests'),
    ('Eye movement test (pen test)','eye movement test (pen test)'),
    ('Blood test','blood test'),
    ('Other','Other'),
    )

REASONS = (
    ('Speeding'),('Swerving'), ('Illegal maneuver'),
    ('Reckless driving'), ('Equipment violation (missing headlight, excessive window tinting, etc.)'),
    ('DUI checkpoint'), ('Other'),
    )

SITUATION = (
    ('I was questioned'),
    ('I was detained'),
    ('I was arrested'),
    ('I was formally charged with a crime')
    )

CHOICES1 = (('1', 'Yes',), ('2', 'No',),('3','Not Sure',))
CHOICES2 = (('1', 'Male',), ('2', 'Female',))
CHOICES3 = (('1', 'Yes',), ('2', 'No',))
CHOICES4 = (('1','Morning'),('2','Afternoon'),('3','Evening'),('4','Late Night'))
CHOICES5 = (('1','No'),('2','Yes, I do'),('3','Yes, my partner does'),('4','Yes, we both do'),('5','I\'m not sure'))
CHOICES6 = (('1','Buying a business'),('2','Selling a business'),('3','Merging with another company'))
CHOICES7 = (('1','Buying an estate'),('2','Selling an estate'))
CHOICES8 = (('1','Condominium'),('2','Single family home'),('3','Multi-family complex'),
    ('4','Office building'),('5','Shopping center'),('6','Land'),('7','Industrial'),('8','Other'))


class divorceForm(forms.Form):
    spouse = forms.CharField(label='What is your Spouse\'s name?', max_length = 25)
    date_of_marriage = forms.DateField(initial=datetime.date,label = 'What was your Date of Marriage?')
    gender = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES2, label = 'Gender of your spouse?')
    mutual = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES1, label = 'Was a pre-nuptial agreement in place at the time of marriage?')
    assets = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,choices=ASSETS, label = 'What Assets did spouse have before marriage? (Select All that Apply)')
    assets_before = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,choices=ASSETS, label = 'What Assets did spouse acquire after marriage? (Select All that Apply)')
    children = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES3, label = 'Do you have children?')
    custody = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES1, label = 'Will either spouse be asking for child support?')
    budget = forms.CharField(label='What is your estimated budget?')
    details = forms.CharField(label='Further Details')

class duiForm(forms.Form):
    date_of_citation = forms.DateField(initial = datetime.date , label = 'When did you receive the DUI citation?');
    tests = forms.MultipleChoiceField(widget = forms.CheckboxSelectMultiple,choices = TESTS,
        label =  'What sobriety tests did the officer perform to measure your intoxication level? (Select all that apply)')
    bac = forms.DecimalField(label = 'If applicable, What was your Blood Alcohol Content (BAC)?',decimal_places=2)
    time_of_day = forms.ChoiceField(widget = forms.RadioSelect, label = 'What time of day were you pulled over?', choices = CHOICES4)
    reason = forms.MultipleChoiceField(widget = forms.CheckboxSelectMultiple, choices = REASONS, label = 'Why were you pulled Over? (Select all that apply)')
    past = forms.ChoiceField(widget = forms.RadioSelect, choices = CHOICES3, label = 'Have you had a DUI in the past?')
    next_date = forms.DateField(initial = datetime.now() + timedelta(days = 7), label = 'When is your next court date?')
    budget = forms.DecimalField(label='What is your estimated budget?',max_digits=6, decimal_places=2)
    details = forms.CharField(label = 'Further Details')

class criminalForm(forms.Form):
    offense = forms.CharField(label = 'What is the name of the offense?')
    offense_date = forms.DateField(initial = datetime.date, label = 'What date did the incident occur?')
    situation = forms.MultipleChoiceField(widget = forms.CheckboxSelectMultiple, choices = SITUATION, label = 'Which of the following best describe your situation?')
    agency = forms.CharField(label = 'What was the law enforcement agency involved?')
    court_past = forms.ChoiceField(widget = forms.RadioSelect, label = 'Have you already been to court for this matter?', choices = CHOICES3)
    next_date = forms.DateField(initial = datetime.now() + timedelta(days = 7), label = 'When is your next court date?')
    worked = forms.ChoiceField(widget = forms.RadioSelect ,label = 'Have you previously worked with a lawyer on this matter?', choices = CHOICES3)
    budget = forms.DecimalField(label='What is your estimated budget?',max_digits=6, decimal_places=2)
    details = forms.CharField(label = 'Further Details')

class prenupForm(forms.Form):
    partner = forms.CharField(label = 'What is your partner\'s name?', max_length = 25)
    assets = forms.MultipleChoiceField(widget = forms.CheckboxSelectMultiple, choices = ASSETS, 
        label = 'Which assests do you own that will be part of the pre-nuptial agreement? (Select all that apply)')
    debt = forms.ChoiceField(widget = forms.RadioSelect, choices = CHOICES5, label = 'Do you or your partner have any debt?')
    debt_details = forms.CharField(label = 'If yes, please explain the type of the debt and approximate amount')
    assets_exclude = forms.ChoiceField(widget = forms.RadioSelect, choices = CHOICES1, 
        label = 'Are there any assets that you or your partner would like to exclude from the pre-nuptial agreement?')
    exclude_details = forms.CharField(label = 'If yes, Please explain')
    budget = forms.DecimalField(label='What is your estimated budget?',max_digits=6, decimal_places=2)

class mergerForm(forms.Form):
    types = forms.ChoiceField(widget = forms.RadioSelect, choices = CHOICES6, label = 'Which of the following do you need help?')
    names = forms.CharField(label  = 'What are the names of all the parties involved in the transaction?')
    circumstances = forms.CharField(label = 'Describe the circumstances of the sale or merger in as much details as possible:')
    need = forms.CharField(label = 'What do you need a lawyer to help with?')
    budget = forms.DecimalField(label='What is your estimated budget?',max_digits=6, decimal_places=2)

class estateForm(forms.Form):
    types  = forms.ChoiceField(widget = forms.RadioSelect, choices = CHOICES7, label = 'What do you want to do?')
    property_type = forms.ChoiceField(widget = forms.RadioSelect, choices = CHOICES8, label = 'What type of property is involved?')
    details = forms.CharField(label= 'Describe your legal issues in as much details as possible:')
    need = forms.CharField(label = 'What do you need a lawyer to help with?')
    budget = forms.DecimalField(label='What is your estimated budget?',max_digits=6, decimal_places=2)

lawyered/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm, divorceForm, duiForm, criminalForm, prenupForm, mergerForm, estateForm
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from .models import person
# Create your views here.
def index(request) :
	return render(request, 'lawyered/index.html')
	
def login(request):
	if request.method== 'POST':

		form = LoginForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = authenticate(username=cd['username'], password=cd['password'])
			username = form.cleaned_data['username']
			if user is not None:
				#login(request,user)
				return render(request,'lawyered/dashboard.html', {'username': username})
			else:
				return render(request, 'lawyered/invalid.html')

	else:
		form = LoginForm()
		return render(request, 'lawyered/login.html', {'form': form})
	

#@login_required
#def dashboard(request):
#	return render(request,'lawyered/dashboard.html',{'section': 'dashboard'})

def register(request):
	if request.method == 'POST':
		user_form = UserRegistrationForm(request.POST)
		if user_form.is_valid():
			# Create a new user object but avoid saving it yet
			new_user = user_form.save(commit=False)
			# Set the chosen password
			new_user.set_password(user_form.cleaned_data['password'])
			# Save the User object
			new_user.save()
			return render(request,'lawyered/register_done.html')
	else:
		user_form = UserRegistrationForm()
	return render(request,'lawyered/register.html',{'user_form': user_form})

@login_required
def dashboard(request):
	return render(request, 'lawyered/dashboard.html')


def person_list(request):
	persons = person.objects.all()
	query = request.GET.get("q")
	if query:
		persons = persons.filter(area__contains = query)
	return render(request,'lawyered/search.html',{'persons': persons})
	
def divorce(request):
	if request.method== 'POST':

		form = divorceForm(request.POST)
		if form.is_valid():
			
			return render(request,'lawyered/done.html')

	else:
		form = divorceForm()
		return render(request, 'lawyered/divorce.html', {'form': form})
	

lawyered/templates/lawyered/dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

    <title>Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="{%static 'lawyered/assets/css/bootstrap.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{%static 'lawyered/assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{%static 'lawyered/assets/css/zabuto_calendar.css' %}">
    <link rel="stylesheet" type="text/css" href="{%static 'lawyered/assets/js/gritter/css/jquery.gritter.css' %}" />
    <link rel="stylesheet" type="text/css" href="{%static 'lawyered/assets/lineicons/style.css' %}">    
    
    <!-- Custom styles for this template -->
    <link href="{%static 'lawyered/assets/css/style.css' %}" rel="stylesheet">
    <link href="{%static 'lawyered/assets/css/style-responsive.css' %}" rel="stylesheet">

    <script src="{%static 'lawyered/assets/js/chart-master/Chart.js' %}"></script>
  </head>

  <body>

  <section id="container" >
      <!--header start-->
      <header class="header black-bg">
            <!--logo start-->
            <a href="{% url 'lawyered:index' %}" class="logo"><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; LAWYERED</b></a>
            <!--logo end-->
            <div class="top-menu">
				<ul class="nav pull-right top-menu">
					<li><a class="TopMenu" href="#">How it Works?</a></li>
					<li><a class="TopMenu" href="#">About</a></li>
					<li><a class="TopMenu" href="#">Contact Us</a></li>
					<li><a class="logout" href="{% url 'lawyered:login' %}">Logout</a></li>
            	</ul>
            </div>
        </header>
      <!--header end-->
      
      <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
              
              	  <p class="centered"><a href="profile.html"><img src="{%static 'lawyered/assets/img/ui-sam.jpg' %}" class="img-circle" width="60"></a></p>
              	  <h5 class="centered">{{ username }}</h5>
              	  	
                  <li class="mt">
                      <a class="active" href="{% url 'lawyered:dashboard' %}">
                          <i class="fa fa-dashboard"></i>
                          <span>Dashboard</span>
                      </a>
                  </li>
				  
				  <li class="mt">
                       <a href="{% url 'lawyered:search' %}">
						  <i class="fa fa-search"></i>
                          <span>Search/Browse</span>
                      </a>
                  </li>
				  
				  <li class="mt">
                       <a href="{% url 'lawyered:divorce' %}">
						  <i class="fa fa-tasks"></i>
                          <span>Add a new Case</span>
                      </a>
                  </li>

                 
              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      
      
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper site-min-height">
			<h3><i class="fa fa-angle-right"></i> Your Cases</h3>

              <div class="row mt">
          		<div class="col-lg-12">
          		
					<!-- 1st ROW OF PANELS -->
					<div class="row">
						<div class="col-lg-4 col-md-4 col-sm-4 mb">
							<div class="product-panel-2 pn">
								<img src="{%static 'lawyered/assets/img/crime.jpg' %}" width="150" alt=" ">
								<h5 class="mt">Murder</h5>
								<h6>Lawyer Approval Pending</h6>
								<button class="btn btn-small btn-theme04">FULL REPORT</button>
							</div>
						</div><!--/col-md-4 -->
					
						<div class="col-lg-4 col-md-4 col-sm-4 mb">
							<div class="product-panel-2 pn">
								<img src="{%static 'lawyered/assets/img/family.jpg' %}" width="150" alt=" ">
								<h5 class="mt">Divorce</h5>
								<h6>Appointment-3/10/2016</h6>
								<button class="btn btn-small btn-theme04">FULL REPORT</button>
							</div>
						</div><!--/col-md-4 -->
					
					</div><!--/END 1ST ROW OF PANELS -->
					
					<!-- 2ND ROW OF PANELS -->
					<div class="row">
						<div class="col-lg-4 col-md-4 col-sm-4 mb">
							<div class="product-panel-2 pn">
								<img src="{%static 'lawyered/assets/img/Document.jpg' %}" width="150" alt=" ">
								<h5 class="mt">Murder</h5>
								<h6>Lawyer Approval Pending</h6>
								<button class="btn btn-small btn-theme04">FULL REPORT</button>
							</div>
						</div><!--/col-md-4 -->
						
						<div class="col-lg-4 col-md-4 col-sm-4 mb">
							<div class="product-panel-2 pn">
								<img src="{%static 'lawyered/assets/img/theft.jpg' %}" width="150" alt=" ">
								<h5 class="mt">Murder</h5>
								<h6>Lawyer Approval Pending</h6>
								<button class="btn btn-small btn-theme04">FULL REPORT</button>
							</div>
						</div><!--/col-md-4 -->
						
						
            		 </div><!--/row -->
            	</div>
            </div>


          </section>
      </section>

      <!--main content end-->

  </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{%static 'lawyered/assets/js/jquery.js' %}"></script>
    <script src="{%static 'lawyered/assets/js/jquery-1.8.3.min.js' %}"></script>
    <script src="{%static 'lawyered/assets/js/bootstrap.min.js' %}"></script>
    <script class="include" type="text/javascript" src="{%static 'lawyered/assets/js/jquery.dcjqaccordion.2.7.js' %}"></script>
    <script src="{%static 'lawyered/assets/js/jquery.scrollTo.min.js' %}"></script>
    <script src="{%static 'lawyered/assets/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
    <script src="{%static 'lawyered/assets/js/jquery.sparkline.js' %}"></script>


    <!--common script for all pages-->
    <script src="{%static 'lawyered/assets/js/common-scripts.js' %}"></script>
    
    <script type="text/javascript" src="{%static 'lawyered/assets/js/gritter/js/jquery.gritter.js' %}"></script>
    <script type="text/javascript" src="{%static 'lawyered/assets/js/gritter-conf.js' %}"></script>

    <!--script for this page-->
    <script src="{%static 'lawyered/assets/js/sparkline-chart.js' %}"></script>    
	<script src="{%static 'lawyered/assets/js/zabuto_calendar.js' %}"></script>	
	
	<script type="text/javascript">
        $(document).ready(function () {
        var unique_id = $.gritter.add({
            // (string | mandatory) the heading of the notification
            title: 'Welcome to LAWYERED!',
            // (string | mandatory) the text inside the notification
            text: 'See your cases, search or browse for lawyers or add a new case. Start Consulting right here right now!.',
            // (string | optional) the image to display on the left
            //image: '{%static 'lawyered/assets/img/ui-sam.jpg' %}',
            // (bool | optional) if you want it to fade out on its own or just sit there
            sticky: true,
            // (int | optional) the time you want it to be alive for before fading out
            time: '',
            // (string | optional) the class name you want to apply to that specific message
            class_name: 'my-sticky-class'
        });

        return false;
        });
	</script>
	
	<script type="application/javascript">
        $(document).ready(function () {
            $("#date-popover").popover({html: true, trigger: "manual"});
            $("#date-popover").hide();
            $("#date-popover").click(function (e) {
                $(this).hide();
            });
        
            $("#my-calendar").zabuto_calendar({
                action: function () {
                    return myDateFunction(this.id, false);
                },
                action_nav: function () {
                    return myNavFunction(this.id);
                },
                ajax: {
                    url: "show_data.php?action=1",
                    modal: true
                },
                legend: [
                    {type: "text", label: "Special event", badge: "00"},
                    {type: "block", label: "Regular event", }
                ]
            });
        });
        
        
        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
    </script>
  

  </body>
</html>

lawyered/templates/lawyered/done.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

    <title>Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="{%static 'lawyered/assets/css/bootstrap.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{%static 'lawyered/assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{%static 'lawyered/assets/css/zabuto_calendar.css' %}">
    <link rel="stylesheet" type="text/css" href="{%static 'lawyered/assets/js/gritter/css/jquery.gritter.css' %}" />
    <link rel="stylesheet" type="text/css" href="{%static 'lawyered/assets/lineicons/style.css' %}">    
    
    <!-- Custom styles for this template -->
    <link href="{%static 'lawyered/assets/css/style.css' %}" rel="stylesheet">
    <link href="{%static 'lawyered/assets/css/style-responsive.css' %}" rel="stylesheet">

    <script src="{%static 'lawyered/assets/js/chart-master/Chart.js' %}"></script>
  </head>

  <body>

  <section id="container" >
      <!--header start-->
      <header class="header black-bg">
            <!--logo start-->
            <a href="{% url 'lawyered:index' %}" class="logo"><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; LAWYERED</b></a>
            <!--logo end-->
            <div class="top-menu">
				<ul class="nav pull-right top-menu">
					<li><a class="TopMenu" href="#">How it Works?</a></li>
					<li><a class="TopMenu" href="#">About</a></li>
					<li><a class="TopMenu" href="#">Contact Us</a></li>
					<li><a class="logout" href="{% url 'lawyered:login' %}">Logout</a></li>
            	</ul>
            </div>
        </header>
      <!--header end-->
      
      <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
              
              	  <p class="centered"><a href="profile.html"><img src="{%static 'lawyered/assets/img/ui-sam.jpg' %}" class="img-circle" width="60"></a></p>
              	  <h5 class="centered">{{ username }}</h5>
              	  	
                  <li class="mt">
                      <a class="active" href="{% url 'lawyered:dashboard' %}">
                          <i class="fa fa-dashboard"></i>
                          <span>Dashboard</span>
                      </a>
                  </li>
				  
				  <li class="mt">
                       <a href="{% url 'lawyered:search' %}">
						  <i class="fa fa-search"></i>
                          <span>Search/Browse</span>
                      </a>
                  </li>
				  
				  <li class="mt">
                       <a href="{% url 'lawyered:divorce' %}">
						  <i class="fa fa-tasks"></i>
                          <span>Add a new Case</span>
                      </a>
                  </li>

                 
              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      
      
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper site-min-height">
			
          <h1>your case is successfully submitted!!</h1>
      </section>

      <!--main content end-->

  </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{%static 'lawyered/assets/js/jquery.js' %}"></script>
    <script src="{%static 'lawyered/assets/js/jquery-1.8.3.min.js' %}"></script>
    <script src="{%static 'lawyered/assets/js/bootstrap.min.js' %}"></script>
    <script class="include" type="text/javascript" src="{%static 'lawyered/assets/js/jquery.dcjqaccordion.2.7.js' %}"></script>
    <script src="{%static 'lawyered/assets/js/jquery.scrollTo.min.js' %}"></script>
    <script src="{%static 'lawyered/assets/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
    <script src="{%static 'lawyered/assets/js/jquery.sparkline.js' %}"></script>


    <!--common script for all pages-->
    <script src="{%static 'lawyered/assets/js/common-scripts.js' %}"></script>
    
    <script type="text/javascript" src="{%static 'lawyered/assets/js/gritter/js/jquery.gritter.js' %}"></script>
    <script type="text/javascript" src="{%static 'lawyered/assets/js/gritter-conf.js' %}"></script>

    <!--script for this page-->
    <script src="{%static 'lawyered/assets/js/sparkline-chart.js' %}"></script>    
	<script src="{%static 'lawyered/assets/js/zabuto_calendar.js' %}"></script>	
	
	<script type="text/javascript">
        $(document).ready(function () {
        var unique_id = $.gritter.add({
            // (string | mandatory) the heading of the notification
            title: 'Welcome to LAWYERED!',
            // (string | mandatory) the text inside the notification
            text: 'See your cases, search or browse for lawyers or add a new case. Start Consulting right here right now!.',
            // (string | optional) the image to display on the left
            //image: '{%static 'lawyered/assets/img/ui-sam.jpg' %}',
            // (bool | optional) if you want it to fade out on its own or just sit there
            sticky: true,
            // (int | optional) the time you want it to be alive for before fading out
            time: '',
            // (string | optional) the class name you want to apply to that specific message
            class_name: 'my-sticky-class'
        });

        return false;
        });
	</script>
	
	<script type="application/javascript">
        $(document).ready(function () {
            $("#date-popover").popover({html: true, trigger: "manual"});
            $("#date-popover").hide();
            $("#date-popover").click(function (e) {
                $(this).hide();
            });
        
            $("#my-calendar").zabuto_calendar({
                action: function () {
                    return myDateFunction(this.id, false);
                },
                action_nav: function () {
                    return myNavFunction(this.id);
                },
                ajax: {
                    url: "show_data.php?action=1",
                    modal: true
                },
                legend: [
                    {type: "text", label: "Special event", badge: "00"},
                    {type: "block", label: "Regular event", }
                ]
            });
        });
        
        
        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
    </script>
  

  </body>
</html>